require('dotenv').config();

const KEYCLOAK_BASE_URL = process.env.KEYCLOAK_BASE_URL;
const KEYCLOAK_REALM_NAME = process.env.KEYCLOAK_REALM_NAME;
const KEYCLOAK_ADMIN_USERNAME = process.env.KEYCLOAK_ADMIN_USERNAME;
const KEYCLOAK_ADMIN_PASSWORD = process.env.KEYCLOAK_ADMIN_PASSWORD;
const KEYCLOAK_ADMIN_CLIENT_ID = process.env.KEYCLOAK_ADMIN_CLIENT_ID;
const KEYCLOAK_NEW_USER_DEFAULT_PASSWORD = process.env.KEYCLOAK_NEW_USER_DEFAULT_PASSWORD;
const KEYCLOAK_AUTH_CLIENT_ID= process.env.KEYCLOAK_AUTH_CLIENT_ID;
const APP_ID = process.env.APP_ID;
const APP_SECRET = process.env.APP_SECRET;
const PORT = process.env.PORT || 8848;

module.exports = {
    KEYCLOAK_BASE_URL,
    KEYCLOAK_REALM_NAME,
    KEYCLOAK_ADMIN_USERNAME,
    KEYCLOAK_ADMIN_PASSWORD,
    KEYCLOAK_ADMIN_CLIENT_ID,
    KEYCLOAK_NEW_USER_DEFAULT_PASSWORD,
    KEYCLOAK_AUTH_CLIENT_ID,
    APP_ID,
    APP_SECRET,
    PORT
};

