name: Npm Unit Test

on:
  push:
    branches: 
      - master
      - release*
      - feature*
  pull_request:
    branches: 
      - master
      - release*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
    - run: npm install
    - run: npm run test